
package com.livtrip.webservice.hotel;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-12-05T13:14:54.993+08:00
 * Generated source version: 3.1.8
 */

@WebFault(name = "WSFault", targetNamespace = "http://schemas.tourico.com/webservices/faults")
public class IHotelFlowBookHotelV3WSFaultFaultMessage extends Exception {
    
    private com.livtrip.webservice.hotel.WSFault wsFault;

    public IHotelFlowBookHotelV3WSFaultFaultMessage() {
        super();
    }
    
    public IHotelFlowBookHotelV3WSFaultFaultMessage(String message) {
        super(message);
    }
    
    public IHotelFlowBookHotelV3WSFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IHotelFlowBookHotelV3WSFaultFaultMessage(String message, com.livtrip.webservice.hotel.WSFault wsFault) {
        super(message);
        this.wsFault = wsFault;
    }

    public IHotelFlowBookHotelV3WSFaultFaultMessage(String message, com.livtrip.webservice.hotel.WSFault wsFault, Throwable cause) {
        super(message, cause);
        this.wsFault = wsFault;
    }

    public com.livtrip.webservice.hotel.WSFault getFaultInfo() {
        return this.wsFault;
    }
}
